name: Setup Dependencies
description: Sets up Node.js, cache and installs dependencies
inputs:
  GITHUB_TOKEN:
    description: GitHub token to set up remote caching
    required: true
  TURBO_SERVER_TOKEN:
    description: Turborepo token
    required: true
runs:
  using: "composite"
  steps:
    - name: Turborepo Caching Server
      uses: felixmosh/turborepo-gh-artifacts@v3
      with:
        repo-token: ${{ inputs.GITHUB_TOKEN }}
        server-token: ${{ inputs.TURBO_SERVER_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
