name: OpenAI Reviewer 🤖

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request != '' && github.actor == 'teddyjfpender' && contains(github.event.comment.body, 'pls review')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run Review
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GPT_KEY }}
        with:
          debug: false
          review_comment_lgtm: false
          openai_heavy_model: gpt-4