name: API CI
on:
  push:
    branches: [main]
    paths:
      - apps/api/**
  workflow_dispatch:
jobs:
  build_api:
    name: Build and deploy API
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
      - name: Build API
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: yarn build:api
      - name: Deploy edge functions to Netlify
        run: yarn deploy:api --auth $NETLIFY_AUTH_TOKEN
