name: Extension E2E
on:
  workflow_run:
    workflows: ["Extension CI"]
    branches: [main]
    types: [completed]
  workflow_dispatch:
jobs:
  e2e:
    name: Run E2E tests
    env:
      VITE_APP_MODE: web
      VITE_APP_API_URL: https://pallad.deno.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
      - name: Build extension
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_MODE=$VITE_APP_MODE yarn build:extension
      - name: Install Chromium for Playwright
        run: npx playwright install chromium
      - name: Run E2E tests
        run: yarn test:e2e:extension
      - uses: actions/upload-artifact@v3
        with:
          name: pallad-extension-e2e
          path: apps/extension/playwright-report/
