name: Release Workflow 🚀
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version 🏷️'
        required: true
        default: '0.0.1'

jobs:
  build_and_release:
    name: 'Build and Release 🛠️'
    runs-on: ubuntu-latest
    env:
      VITE_APP_MODE: web
      VITE_APP_DEFAULT_NETWORK: Devnet
      NODE_OPTIONS: "--max_old_space_size=4096"
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup env 🌍
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}

      - name: Build extension 🏗️
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_MODE=$VITE_APP_MODE pnpm build:extension

      - name: Create Release 🎉
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: 'Release of version ${{ env.RELEASE_VERSION }} 🚀'
          draft: false
          prerelease: false
          files: apps/extension/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
