name: Pallad Release Workflow 🚀
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version 🏷️'
        required: true
        default: '0.0.1'
      tag_name:
        description: 'Tag name for the release 🔖'
        required: true
      release_name:
        description: 'Name of the release 📛'
        required: true
      release_body:
        description: 'Release notes body 📝'
        required: true
      draft:
        description: 'Mark release as draft? 🚧'
        required: true
        type: boolean
      prerelease:
        description: 'Mark as prerelease? 🚀'
        required: true
        type: boolean
      generate_release_notes:
        description: 'Generate release notes automatically? 📃'
        required: true
        type: boolean

jobs:
  build_and_release:
    name: 'Build and Release 🛠️'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup env 🌍
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}

      - name: Build extension 🏗️
        env:
          VITE_APP_MODE: web
          VITE_APP_DEFAULT_NETWORK: Devnet
          NODE_OPTIONS: "--max_old_space_size=4096"
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_MODE=$VITE_APP_MODE pnpm build:extension

      - name: Compress dist folder
        run: |
          cd apps/extension
          zip -r ../../pallad-chromium.zip dist/

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Create Release 🎉
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: pallad-chromium.zip
          generate_release_notes: ${{ github.event.inputs.generate_release_notes }}