name: Extension CI
on:
  push:
    branches: [main]
    paths:
      - apps/extension/**
      - packages/features/**
  pull_request:
    branches: [main]
    paths:
      - apps/extension/**
      - packages/features/**
jobs:
  test_and_build:
    name: 'Build and test'
    env:
      VITE_APP_MODE: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
      - name: Build extension
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_MODE=$VITE_APP_MODE yarn build:extension
      - name: Run unit tests
        run: yarn test:unit
      - uses: actions/upload-artifact@v3
        with:
          name: pallad-chromium
          path: apps/extension/dist/
