name: Release Workflow 🚀
on:
  push:
    branches: [chore/example-release-workflow]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version 🏷️'
        required: true
        default: '0.0.1'

jobs:
  build_and_release:
    name: 'Build and Release 🛠️'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup env 🌍
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}

      - name: Build extension 🏗️
        env:
          VITE_APP_MODE: web
          VITE_APP_DEFAULT_NETWORK: Devnet
          NODE_OPTIONS: "--max_old_space_size=4096"
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_MODE=$VITE_APP_MODE pnpm build:extension

      - name: Compress dist folder
        run: |
          cd apps/extension/dist/
          zip -r ../../../../dist.zip .

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Create Release 🎉
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Release ${{ steps.tag.outputs.release_tag }}
          body: 'Release of version ${{ steps.tag.outputs.release_tag }} 🚀'
          draft: false
          prerelease: false
          files: dist.zip