on:
  push:
    branches:
      - main
    paths:
      - apps/website/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build file
        run: yarn build:website
      - name: Publish website to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=apps/website/.next --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
